### ISSUE TITLE
Should we change secret_key in .env file?

### ISSUE THREAD

**Issue by VityaSchel** [vicalloy/oidc-server#1]
Hello, there seems to be a pre-defined secret_key in .env file, the word secret tells me to change this from default value, should we do that? If yes, what algorithm was used to generate this key and what are requirements for it?

**Comment by vicalloy** [comment]
Yes, you should change it.

**Comment by VityaSchel** [comment]
> Yes, you should change it.

Ok, can you tell what are the requirements and how to generate it?

**Comment by vicalloy** [comment]
It's a random string, you can use `openssl rand -hex 28` to generate it.
